### ISSUE TITLE
Support OKIB in multiple text channels

### ISSUE THREAD

**Issue by jmrico01** [impossible-bosses/ibce-bots#6]
Maybe this already 100% works in different channels. However, I would like to see support for independent (simultaneous/non-interfering) OKIB gathers in multiple channels, which is definitely not supported. I think `pub-games` channel or `inhouse-high-diff` channel can be dedicated to BNet gathers, to get NA/bnet ppl more M+ practice.

**Comment by Archimonde666** [comment]
I'm still not rly convinced of the usefulness of such a feature. if you're planning on hosting with non-IBCE players (e.g. pubs) you should NOT use the !okib feature, just because it would confuse the players. I agree with that the channel it's into might contribute to the knowledge of what the gather is for : A gather into pub-games is not likely to be with 8 IBCE.

Therefore i don't understand what's the real purpose of this ; if you not 8, you just host a pub : people see that it's in lobby and can join/not join and tell the host if they're planning to join into discord. If you actually :noib: you just leave the lobby and that's it.  

On top of that it require substantial changes in the code (need to transform everything into python lists)

**Comment by jmrico01** [comment]
Yeah this isn't 100% necessary. I think the code might benefit from such a change, but I don't feel too strongly about this anymore. Maybe typical_methods has better ideas on useful stuff to implement, and whether !okib for BNet still makes sense or not, idk.

**Comment by jmrico01** [comment]
eh, not necessary. https://github.com/impossible-bosses/ibce-bots/issues/14 is enough

**Comment by Archimonde666** [comment]
Reopened with the growth of the bnet community and https://github.com/impossible-bosses/ibce-bots/issues/43

**Comment by jmrico01** [comment]
We don't have to make this as complicated as I described, since ENT and pubs happen at different times anyway - no need for 2 simultaneous gathers. Maybe just have the gather look slightly differently when in `#general-chat` vs `#pub-games` channels, and the react permissions are completely open to anyone when in `#pub-games`.

**Comment by Archimonde666** [comment]
Ha-grid for now i guess i'll just enable !okib for the pub host role when on the pub channel
